import {
	IconAI,
	IconCSS,
	IconDocker,
	IconFigma,
	IconFSD,
	IconGithub,
	IconHTML,
	IconJS,
	IconMobX,
	IconPost,
	IconPS,
	IconReact,
	IconSASS,
	IconSB,
	IconTS,
	IconTW,
	IconVite,
	IconVS,
} from '@/shared/assets/icons';

import type { Technology } from '.';

export const technologies: Technology[] = [
	{ name: 'HTML', icon: IconHTML },
	{ name: 'CSS3', icon: IconCSS },
	{ name: 'React', icon: IconReact, description: 'Компонентный UI' },
	{ name: 'TypeScript', icon: IconTS, description: 'Типизация' },
	{ name: 'FSD', icon: IconFSD, description: 'Модульность' },
	{ name: 'JavaScript', icon: IconJS },
	{ name: 'Tailwind', icon: IconTW, description: 'Быстрая вёрстка' },
	{ name: 'MobX', icon: IconMobX, description: 'Реактивность' },
	{ name: 'Supabase', icon: IconSB, description: 'Бэкенд' },
	{ name: 'Vite', icon: IconVite, description: 'Быстрая сборка' },
	{ name: 'Photoshop', icon: IconPS },
	{ name: 'Illustrator', icon: IconAI },
	{ name: 'Figma', icon: IconFigma },
	{ name: 'Docker', icon: IconDocker },
	{ name: 'VS Code', icon: IconVS },
	{ name: 'GitHub', icon: IconGithub },
	{ name: 'PostgreSQL', icon: IconPost },
	{ name: 'SASS', icon: IconSASS },
];
