import {
	IconAI,
	IconCSS,
	IconDocker,
	IconFigma,
	IconFSD,
	IconGithub,
	IconHTML,
	IconJS,
	IconMobX,
	IconPost,
	IconPS,
	IconReact,
	IconSASS,
	IconSB,
	IconTS,
	IconTW,
	IconVite,
	IconVS,
} from '@/shared/assets/icons';

import type { Technology } from '.';

export const technologies: Technology[] = [
	{ name: 'HTML', icon: IconHTML, description: 'Основа разметки' },
	{ name: 'CSS3', icon: IconCSS, description: 'Стилизация' },
	{ name: 'React', icon: IconReact, description: 'Компонентный UI' },
	{ name: 'TypeScript', icon: IconTS, description: 'Типизация' },
	{ name: 'FSD', icon: IconFSD, description: 'Модульность' },
	{ name: 'JavaScript', icon: IconJS, description: 'Логика' },
	{ name: 'Tailwind', icon: IconTW, description: 'Быстрая вёрстка' },
	{ name: 'MobX', icon: IconMobX, description: 'Реактивность' },
	{ name: 'Supabase', icon: IconSB, description: 'Бэкенд' },
	{ name: 'Vite', icon: IconVite, description: 'Быстрая сборка' },
	{ name: 'Photoshop', icon: IconPS, description: 'Графика и ретушь' },
	{ name: 'Illustrator', icon: IconAI, description: 'Вектор и логотипы' },
	{ name: 'Figma', icon: IconFigma, description: 'Дизайн и прототипы' },
	{ name: 'Docker', icon: IconDocker, description: 'Контейнеризация' },
	{ name: 'VS Code', icon: IconVS, description: 'Среда разработки' },
	{ name: 'GitHub', icon: IconGithub, description: 'Командная работа' },
	{ name: 'PostgreSQL', icon: IconPost, description: 'База данных' },
	{ name: 'SASS', icon: IconSASS, description: 'Стили с логикой' },
];
